services:
  frontend:
    build: 
      context: ./frontend
      target: product
    restart: always
    ports:
      - "5173:80"
    env_file:
      - ./config/frontend.env
  
  backend:
    build: 
      context: ./backend
      target: Develop
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./config/backend.env
